### ISSUE TITLE
Fix old posts

### ISSUE THREAD

**Issue by luserx0** [luserx0/Casper-Blog#15]
Fix Markdown on old projects.

**Comment by luserx0** [comment]
- Review syntax and grammar errors
- Double check that the Markdown used works properly

**Comment by luserx0** [comment]
Please do this, it's the fastest and easiest of all and by far the most important in terms of aesthetics

**Comment by An0u** [comment]
Done with the reviewal of syntax and grammatical errors.
Currently old_blog posts reside in the .gitignore folder and I haven't pushed them yet
